#!/usr/bin/env node
// Write `src/version.generated.ts` from the `version` field of `package.json`.
//
// The package must report the version it was published as, and it must do so without reading a
// file at runtime: `createRequire(import.meta.url)("../package.json")` cannot be emitted into CJS
// and defeats every bundler, which rules out the runtime read this replaces.
//
// The generated module is git-ignored and regenerated by `npm run build` (and by `prepare`, so a
// fresh clone can typecheck before it has ever built). `prepack` runs `npm run build`, and npm runs
// `prepack` AFTER `@semantic-release/npm` has written the resolved version into `package.json` in
// the release runner — that ordering is what makes the published artifact carry the real version.
// Generating from `prepare` alone would not: npm runs `prepack` before `prepare`.
//
// A checkout reports `0.0.0`, because that is the permanent placeholder `package.json` carries in
// git (see `.rules/RELEASE.md`). That is intended, not a bug to fix by hardcoding a number.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = typeof manifest.version === "string" ? manifest.version : "0.0.0";

const contents = `// GENERATED by scripts/generate-version.mjs — do not edit, do not commit.
/** The version written into \`package.json\` when this artifact was built. */
export const generatedVersion = ${JSON.stringify(version)};
`;

const target = join(root, "src", "version.generated.ts");
const current = (() => {
  try {
    return readFileSync(target, "utf8");
  } catch {
    return undefined;
  }
})();

// Idempotent: rewriting an identical file would churn mtimes and defeat watch-mode callers.
if (current !== contents) {
  writeFileSync(target, contents);
}
